Repository AY2425S1-CS2103T-T17-2/tp, pull requests merged in 2024-10, with the labels that each got.

#51 Enable deleting customers' contacts based on their names
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement

#57 Add test coverage for code added
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Bug

#63 Add test to Comment.java
  src/main/java/seedu/address/model/person/Comment.java
  src/test/java/seedu/address/model/person/CommentTest.java
Labels: severity.Low
